angular.module('amCompanion').run(['$templateCache', function($templateCache) {
  'use strict';

  $templateCache.put('index.html',
    "<!DOCTYPE html><!--[if lt IE 7]><html lang=\"en\" ng-app=\"amCompanion\" class=\"no-js lt-ie9 lt-ie8 lt-ie7\"><![endif]--><!--[if IE 7]><html lang=\"en\" ng-app=\"amCompanion\" class=\"no-js lt-ie9 lt-ie8\"><![endif]--><!--[if IE 8]><html lang=\"en\" ng-app=\"amCompanion\" class=\"no-js lt-ie9\"><![endif]--><!--[if gt IE 8]><!--><html lang=en ng-app=amCompanion class=no-js><!--<![endif]--><head><meta charset=utf-8><meta http-equiv=X-UA-Compatible content=\"IE=edge\"><title>Am Companion</title><meta name=description content=\"\"><meta name=viewport content=\"width=device-width,initial-scale=1,maximum-scale=1,user-scalable=0\"><meta name=apple-mobile-web-app-capable content=\"yes\"><base href=\"/\"><link rel=\"stylesheet prefetch\" href=\"/dist/style.min.css\"></head><body id=am-companion class=fade-view ng-controller=RootController><div id=main-container ng-view class=view></div><div class=\"notif-update ng-hide\" ng-show=\"updateStatus != 0\" ng-class=\"{'tall':updateStatus == 3}\"><div ng-if=\"updateStatus == 1\">Mise à jour en cours <i class=\"fa fa-circle-o-notch fa-spin\"></i></div><div ng-if=\"updateStatus == 2\">Mise à jour effectuée <i class=\"fa fa-check fa-green\"></i></div><div ng-if=\"updateStatus == 3\"><div>Mise à jour échouée <i class=\"fa fa-times fa-red\"></i></div><div class=row><div class=\"columns small-6\"><button ng-click=sendRapport() class=\"btn btn-steria btn-xs small-10 small-centered push-1 columns\">Envoyer le rapport</button></div><div class=\"columns small-6\"><button ng-click=closeNotif() class=\"btn btn-steria btn-xs small-10 small-centered columns\">Fermer</button></div></div></div></div><script src=/dist/script.min.js></script></body></html>"
  );


  $templateCache.put('partials/embed/employee.html',
    "<div class=row ng-click=openEmployeeView()><div class=\"item employee columns small-12\" ng-class=\"{'last':last}\"><div class=row><i class=\"small-2 user-icon fa fa-flag-o status-{{employee.Status}}\"></i><div class=\"user-info columns small-9\"><div><span ng-bind=employee.FirstName></span> <span ng-bind=employee.LastName></span></div><div ng-if=\"lastLink != undefined\" class=sub-info><i class=\"glyphicon glyphicon-map-marker\"></i> <span ng-bind=\"lastLink.DateTimestamp|date:'dd/MM/yyyy'\"></span>, <span ng-bind=lastLink.Type|truncate:20></span></div><div ng-if=\"lastLink == undefined\">Pas de rendez vous</div></div><div class=\"next columns small-1\"><i class=\"fa-angle-right fa\"></i></div></div></div></div>"
  );


  $templateCache.put('partials/full/employee.html',
    "<div class=container id=employee-view><amc-header go-back-handler=goBack() libelle=nomPrenom home-display=false edit-mode=editMode></amc-header><div class=content><div class=row><div class=\"separator columns small-12\"><span class=text>Objectifs</span> <span class=\"action float-right\" ng-click=createNewObjective()><button class=\"btn add-new\" ng-disabled=editMode><span class=\"fa fa-plus\"></span></button></span></div><div class=\"item columns small-12\" ng-repeat=\"objective in selectedEmployee.Objectives\" ng-click=\"showFullObjective( $index )\"><div class=\"columns small-10\"><progress-arc complete=objective.ProgressionPercent/100 stroke=progressColors[$index]></progress-arc><div class=percent ng-class=\"{'cent':objective.ProgressionPercent == 100}\">{{objective.ProgressionPercent}}%</div><div class=text>{{objective.Text}}</div></div><div ng-if=!editMode class=\"next columns small-1\"></div><div ng-if=!editMode class=\"next columns small-1\"><i class=\"fa-angle-right fa\"></i></div><div ng-if=editMode class=\"text-center next columns small-2\" ng-click=\"deleteObjective($event, $index)\"><span class=\"fa fa-trash-o red\"></span></div></div><div class=\"separator columns small-12\"><span class=text>Entretiens</span> <span class=\"action float-right\" ng-click=createNewLink()><button class=\"btn add-new\" ng-disabled=editMode><span class=\"fa fa-plus\"></span></button></span></div><div class=\"item columns small-12\" ng-repeat=\"link in selectedEmployee.Links | orderBy:'date':'reverse'\" ng-click=\"showFullLink( link )\"><div class=row><div class=\"small-2 columns\"><i class=\"fa item-icon-left\" ng-class=getIcon(link.Type)></i></div><div class=\"small-8 columns\"><div>{{link.Type}}</div><div>{{link.DateTimestamp|date:'d MMMM yyyy'}}</div></div><div ng-if=!editMode class=\"next columns small-1\"></div><div ng-if=!editMode class=\"next columns small-1\"><i class=\"fa-angle-right fa\"></i></div><div ng-if=editMode class=\"text-center next columns small-2\" ng-click=\"deleteLink($event, $index)\"><span class=\"fa fa-trash-o red\"></span></div></div></div></div></div></div>"
  );


  $templateCache.put('partials/full/home.html',
    "<div id=home class=container><amc-header home-display=true></amc-header><div class=content><div class=row><div class=\"separator columns small-12\"><span class=text>Collaborateurs</span></div><div ng-repeat=\"employee in employees|orderBy:'dateMax' track by employee.id \" class=\"columns sm\"><embed-employee employee=employee last=$last></embed-employee></div></div></div></div>"
  );


  $templateCache.put('partials/full/link.html',
    "<div class=container id=employee-view><amc-header go-back-handler=goBack() libelle=nomPrenom home-display=false edit-mode=editMode></amc-header><div class=content><div class=row><div class=\"separator columns small-12\"><span class=text>Lieu</span></div><div class=\"item-without-padding columns small-12\"><select ng-model=selectedLink.Type ng-options=\"o as o for o in linkTypes\"></select></div><div class=\"separator columns small-12\"><span class=text>Date</span></div><div class=\"item-without-padding columns small-12\"><input type=date ng-model=selectedDate ng-change=changeSelectedDate()></div><div class=\"separator columns small-12\"><span class=text>Commentaire</span></div><div class=\"item-fit-without-padding columns small-12\"><textarea ng-model=selectedLink.Comment rows=10></textarea></div></div></div></div>"
  );


  $templateCache.put('partials/full/login.html',
    "<div id=loginModal><img id=logo src=\"./img/logo-white.png\"><div class=row><form class=\"columns large-4 large-centered small-10 small-centered center-block\" ng-submit=login() name=loginForm><div class=\"row collapse\"><div class=\"input-group input-group-lg\"><span class=input-group-addon>@</span> <input type=email name=email class=form-control placeholder=\"Adresse mail\" ng-model=credentials.email required></div></div><div class=\"row collapse\"><div class=\"input-group input-group-lg\"><span class=input-group-addon><span class=\"fa fa-lock\"></span></span> <input name=password type=password class=form-control placeholder=\"Mot de passe\" ng-model=credentials.password required></div></div><div class=\"row collapse\"><button type=submit ng-class=\"{'btn-danger':failed,'btn-success':success}\" class=\"btn btn-steria btn-lg btn-block small-10 small-centered columns large-12\" ng-disabled=\"!loginForm.$valid || loading\">{{buttonLabel}}</button></div></form><div class=clear></div></div></div>"
  );


  $templateCache.put('partials/full/objective.html',
    "<div class=container id=employee-view><amc-header go-back-handler=goBack() libelle=nomPrenom home-display=false edit-mode=editMode></amc-header><div class=content><div class=row><div class=\"separator columns small-12\"><span class=text>Intitulé</span></div><div class=\"columns small-12\"><div class=\"input-group input-group-lg columns small-12 small-centered\"><input class=form-control placeholder=Intitulé ng-model=selectedObjective.Text required></div></div><div class=\"separator columns small-12\"><span class=text>Pourcentage d'accomplissement</span></div><div class=\"item columns small-12\"><div class=\"input-group input-group-lg columns small-12 small-centered\"><div class=rzslider><rzslider rz-slider-model=selectedObjective.ProgressionPercent rz-slider-floor=0 rz-slider-ceil=100></rzslider></div></div></div></div></div></div>"
  );


  $templateCache.put('partials/utils/amc_header.html',
    "<nav class=\"navbar navbar-default navbar-fixed-top\" role=navigation><div ng-if=homeDisplay><div class=navbar-header><div class=\"columns small-2\"></div><div class=\"columns small-8 menu-title\"><img src=/img/logo-icon.png id=nav-logo></div><div class=\"columns small-2\" ng-click=disconnect()><span class=\"right-menu-icon fa fa-power-off hv-center\"></span></div></div></div><div ng-if=!homeDisplay class=navbar-header><div class=row><div class=\"columns small-2\" ng-if=editMode ng-click=cancelEditMode()><span class=\"left-menu-icon fa-ban fa hv-center\" style=color:{{cancelColor}}></span></div><div class=\"columns small-2\" ng-if=!editMode ng-click=goBack()><span class=\"left-menu-icon fa fa-arrow-left hv-center\" style=color:{{backColor}}></span></div><div class=\"columns small-8 menu-title\"><span ng-bind=libelle></span></div><div class=\"columns small-2\" ng-if=!editMode ng-click=toggleEditMode()><span class=\"right-menu-icon fa-pencil-square-o fa hv-center\" style=color:{{editColor}}></span></div><div class=\"columns small-2\" ng-if=editMode ng-click=validateEditMode()><span class=\"right-menu-icon fa-check fa hv-center\" style=color:{{validateColor}}></span></div></div></div></nav>"
  );

}]);
